FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src/API

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

CMD ["dotnet", "watch", "run", "--urls=http://+:8080"]
